### ISSUE TITLE
[Bug] SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Kristinita** [Starli0n/SublimeAgentRansack#1]
### 1. Summary

I can not run command `agent_ransack`.

### 2. Expected behavior

Open Agent Ransack with the directory of the current file like package description.

### 3. Actual behavior

I don't can run `agent_ransack` command.

Command don't run via context menu:
folder
![Context menu](http://i.imgur.com/XpfwBQi.png)

If I run command in Sublime Text console, nothing occurs.

```python
sublime.run_command('agent_ransack')
```

I restart Sublime Text → I saw stack trace in console:

```python
reloading plugin SublimeAgentRansack.agent_ransack
Traceback (most recent call last):
  File "D:\Sublime Text 3 x64\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\Sublime Text 3 x64\sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "agent_ransack in D:\Sublime Text 3 x64\Data\Installed Packages\SublimeAgentRansack.sublime-package", line 36
    print "AgentRansack command: " + cmd_line
                                 ^
SyntaxError: invalid syntax
```

### 4. Settings

My AgentRansack  is `C:\Program Files\Mythicsoft\Agent Ransack`.

### 5. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I open any file → I run AgentRansack → I get actual behavior.

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126
**AgentRansack:**
Release Build 865 - 2016.10.19.45457 (x64)

Thanks.

**Comment by Starli0n** [comment]
The plugin is now compatible with `ST3`.

Thank you! You motivated me to switch from `ST2` to `ST3` and I will migrate my plugin little by little.
By chance, AgentRansack is the first one.

By the way, I created a pull request [#6156](https://github.com/wbond/package_control_channel/pull/6156) so that it could be included to Package Control.
